name = "YAXArraysToolbox"
uuid = "fe326ce2-c736-437b-b94b-0bdf007dd2e5"
version = "0.3.5"
authors = ["Daniel E. Pabon-Moreno <dpabon@bgc-jena.mpg.de>", "Alexander J. Winkler", "Gregory Duveiller"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TimeSeries = "9e3dc215-6440-5c97-bce1-76c03772f85e"
YAXArrays = "c21b50f5-aa40-41ea-b809-c0f5e47bfa5c"

[compat]
CairoMakie = "0.12, 0.13, 0.14, 0.15"
GLM = "2.0.0"
GeoMakie = "0.7.16"
StatsBase = "0.34.10"
YAXArrays = "0.5, 0.6, 0.7"
julia = "1.10"

[extras]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "CairoMakie"]
