[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
NeutralLandscapes = "71847384-8354-4223-ac08-659a5128069f"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SkipNan = "aed68c70-c8b0-4309-8cd1-d392a74f991a"
TiledViews = "ab21d65a-3167-428d-8ea2-d01236aa30f2"
YAXArrays = "c21b50f5-aa40-41ea-b809-c0f5e47bfa5c"
YAXArraysToolbox = "fe326ce2-c736-437b-b94b-0bdf007dd2e5"
Zarr = "0a941bbe-ad1d-11e8-39d9-ab76183a1d99"
