[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
YAXArrays = "c21b50f5-aa40-41ea-b809-c0f5e47bfa5c"
YAXArraysToolbox = "fe326ce2-c736-437b-b94b-0bdf007dd2e5"
Zarr = "0a941bbe-ad1d-11e8-39d9-ab76183a1d99"
